pipeline {
    agent any

    options {
        skipDefaultCheckout(true)   // ⛔ Disable Jenkins auto git checkout
    }

    stages {

        stage('Checkout Source') {
            steps {
                // Explicit checkout (clean & controlled)
                git url: 'https://github.com/prasabhi/pyapp.git', branch: 'master'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build \
                    -t chatbot-app \
                    -f chatbot/docker/Dockerfile \
                    .
                '''
            }
        }

        stage('Run Containers') {
            steps {
                sh '''
                  docker compose up -d
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
