pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build \
                  -t chatbot-app \
                  -f chatbot/docker/Dockerfile \
                  .
                '''
            }
        }

        stage('Run Containers') {
            steps {
                dir('chatbot'){
                sh '''
                  docker compose \
                  --project-directory chatbot \
                  -f docker-compose.yml \
                  up -d
                '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
