pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build \
                  -t chatbot-app \
                  -f chatbot/docker/Dockerfile \
                  .
                '''
            }
        }

        stage('Run Containers') {
            steps {
                    sh '''
                    set -eux

                    cd chatbot

                    echo "Current directory:"
                    pwd

                    echo "Monitoring directory contents:"
                    ls -l monitoring

                    test -f monitoring/prometheus.yml

                    docker compose down -v || true
                    docker compose up -d
                    '''
                }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
